#ifndef GUARD_CONSTANTS_FIELDMAP_H
#define GUARD_CONSTANTS_FIELDMAP_H

#define PLAYER_AVATAR_FLAG_ON_FOOT      (1 << 0)
#define PLAYER_AVATAR_FLAG_MACH_BIKE    (1 << 1)
#define PLAYER_AVATAR_FLAG_ACRO_BIKE    (1 << 2)
#define PLAYER_AVATAR_FLAG_SURFING      (1 << 3)
#define PLAYER_AVATAR_FLAG_UNDERWATER   (1 << 4)
#define PLAYER_AVATAR_FLAG_CONTROLLABLE (1 << 5)
#define PLAYER_AVATAR_FLAG_FORCED_MOVE  (1 << 6)
#define PLAYER_AVATAR_FLAG_DASH         (1 << 7)

#endif  // GUARD_CONSTANTS_FIELDMAP_H