gText_Birch_Welcome::
	.string "G'day fuckhead.\p"
	.string "I'm Professor Birch, and I'll be\n"
	.string "subjecting you to the most grueling\l"
	.string "and painful playthrough of Pokémon\l"
	.string "Emerald.\p"
	.string "'The Poison Challenge'\p"
	.string "Your goal is to beat the Pokemon League\n"
	.string "Champion and enter the Hall of Fame.\l"
	.string "Whiting out does not end the challenge.\l"
	.string "Simply reaching the end counts as a\l"
	.string "win. White-outs don't matter.\p"
	.string "So feel free to pass out as much as you\n"
	.string "like?\p"
	.string "$"

gText_ThisIsAPokemon::
	.string "Here's the rules:{PAUSE 96}\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "1. Your entire party loses 1 HP every\n"
	.string "single step. This is non-negotiable.\l"
	.string "Your Pokémon will faint when they hit 0\l"
	.string "HP.\p"
	.string "When all of your Pokémon faint, you will\n"
	.string "white out and return to the last\l"
	.string "visited Pokémon Center.\p"
	.string "2. You may only heal at Pokémon Centers\n"
	.string "and from moves and items you find on\l"
	.string "your journey.\p"
	.string "Purchasing healing items from\n"
	.string "Pokémarts is entirely forbidden.\n"
	.string "Get good scrub.\p"
	.string "3. Don't be a fuckin' bitch. Use your\n"
	.string "knowledge of Pokémon to figure it out\l"
	.string "lol. Also, just note that this challenge\l"
	.string "uses the battle mechanics from\l"
	.string "Generation 8.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Anyway, you look funny. Who are ya?\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy, a girl or another secret\n"
	.string "third thing?\p"
	.string "$"

gText_Birch_WhatsYourName::
	.string "I personally would like to keep calling\n"
	.string "you 'Fuckhead', but I should probably\l"
	.string "ask what your name is.$"

gText_Birch_SoItsPlayer::
	.string "Did I hear that right?? {PLAYER}{KUN}?\p"
	.string "$"

gText_Birch_YourePlayer::
	.string "Yeah, sick. You're {PLAYER}{KUN}, the\n"
	.string "funnycunt who decided to try the\l"
	.string "Poison Challenge.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Alright I suppose you should be on your\n"
	.string "way then.\p"
	.string "Remember, every step counts. Good luck\n"
	.string "out there. I'll be waiting in my lab.{PAUSE 96}$"
